.PHONY: clean All

All:
	@echo "----------Building project:[ Testing2 - Debug ]----------"
	@cd "Testing2" && "$(MAKE)" -f  "Testing2.mk"
clean:
	@echo "----------Cleaning project:[ Testing2 - Debug ]----------"
	@cd "Testing2" && "$(MAKE)" -f  "Testing2.mk" clean
